export const COUNTRIES_CITIES = {
  "Afghanistan": ["Kabul", "Kandahar", "Herat", "Mazar-i-Sharif"],
  "Albania": ["Tirana", "Durrës", "Vlorë", "Shkodër"],
  "Algeria": ["Algiers", "Oran", "Constantine", "Annaba"],
  "Andorra": ["Andorra la Vella", "Escaldes-Engordany"],
  "Angola": ["Luanda", "Huambo", "Lobito", "Benguela"],
  "Argentina": ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "La Plata"],
  "Armenia": ["Yerevan", "Gyumri", "Vanadzor"],
  "Australia": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Canberra", "Gold Coast", "Newcastle"],
  "Austria": ["Vienna", "Graz", "Linz", "Salzburg", "Innsbruck"],
  "Azerbaijan": ["Baku", "Ganja", "Sumqayit"],
  "Bahamas": ["Nassau", "Freeport"],
  "Bahrain": ["Manama", "Riffa", "Muharraq"],
  "Bangladesh": ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet"],
  "Barbados": ["Bridgetown", "Speightstown"],
  "Belarus": ["Minsk", "Gomel", "Mogilev", "Vitebsk"],
  "Belgium": ["Brussels", "Antwerp", "Ghent", "Charleroi", "Liège"],
  "Belize": ["Belize City", "San Ignacio", "Orange Walk"],
  "Benin": ["Cotonou", "Porto-Novo", "Parakou"],
  "Bhutan": ["Thimphu", "Paro", "Punakha"],
  "Bolivia": ["La Paz", "Santa Cruz", "Cochabamba", "Sucre"],
  "Bosnia and Herzegovina": ["Sarajevo", "Banja Luka", "Tuzla", "Zenica"],
  "Botswana": ["Gaborone", "Francistown", "Maun"],
  "Brazil": ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Fortaleza", "Belo Horizonte", "Manaus", "Curitiba", "Recife", "Porto Alegre"],
  "Brunei": ["Bandar Seri Begawan", "Kuala Belait", "Seria"],
  "Bulgaria": ["Sofia", "Plovdiv", "Varna", "Burgas"],
  "Burkina Faso": ["Ouagadougou", "Bobo-Dioulasso"],
  "Burundi": ["Gitega", "Bujumbura"],
  "Cambodia": ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville"],
  "Cameroon": ["Yaoundé", "Douala", "Bamenda", "Garoua"],
  "Canada": ["Toronto", "Montreal", "Vancouver", "Calgary", "Edmonton", "Ottawa", "Winnipeg", "Quebec City", "Hamilton", "Kitchener"],
  "Cape Verde": ["Praia", "Mindelo"],
  "Central African Republic": ["Bangui", "Bimbo"],
  "Chad": ["N'Djamena", "Moundou", "Sarh"],
  "Chile": ["Santiago", "Valparaíso", "Concepción", "La Serena", "Antofagasta"],
  "China": ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu", "Hangzhou", "Wuhan", "Xi'an", "Nanjing", "Tianjin"],
  "Colombia": ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena"],
  "Comoros": ["Moroni", "Mutsamudu"],
  "Congo": ["Brazzaville", "Pointe-Noire"],
  "Costa Rica": ["San José", "Limón", "Alajuela", "Heredia"],
  "Croatia": ["Zagreb", "Split", "Rijeka", "Osijek"],
  "Cuba": ["Havana", "Santiago de Cuba", "Camagüey", "Holguín"],
  "Cyprus": ["Nicosia", "Limassol", "Larnaca", "Paphos"],
  "Czech Republic": ["Prague", "Brno", "Ostrava", "Plzeň"],
  "Denmark": ["Copenhagen", "Aarhus", "Odense", "Aalborg"],
  "Djibouti": ["Djibouti City", "Ali Sabieh"],
  "Dominica": ["Roseau", "Portsmouth"],
  "Dominican Republic": ["Santo Domingo", "Santiago", "La Romana", "San Pedro de Macorís"],
  "Ecuador": ["Quito", "Guayaquil", "Cuenca", "Ambato"],
  "Egypt": ["Cairo", "Alexandria", "Giza", "Shubra El-Kheima", "Port Said"],
  "El Salvador": ["San Salvador", "Santa Ana", "San Miguel"],
  "Equatorial Guinea": ["Malabo", "Bata"],
  "Eritrea": ["Asmara", "Keren", "Massawa"],
  "Estonia": ["Tallinn", "Tartu", "Narva", "Pärnu"],
  "Eswatini": ["Mbabane", "Manzini"],
  "Ethiopia": ["Addis Ababa", "Dire Dawa", "Mek'ele", "Gondar"],
  "Fiji": ["Suva", "Lautoka", "Nadi"],
  "Finland": ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu"],
  "France": ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg", "Montpellier", "Bordeaux", "Lille"],
  "Gabon": ["Libreville", "Port-Gentil"],
  "Gambia": ["Banjul", "Serekunda"],
  "Georgia": ["Tbilisi", "Batumi", "Kutaisi", "Rustavi"],
  "Germany": ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart", "Düsseldorf", "Dortmund", "Essen", "Leipzig"],
  "Ghana": ["Accra", "Kumasi", "Tamale", "Sekondi-Takoradi"],
  "Greece": ["Athens", "Thessaloniki", "Patras", "Heraklion"],
  "Grenada": ["St. George's", "Gouyave"],
  "Guatemala": ["Guatemala City", "Antigua", "Quetzaltenango"],
  "Guinea": ["Conakry", "Nzérékoré", "Kankan"],
  "Guinea-Bissau": ["Bissau", "Bafatá"],
  "Guyana": ["Georgetown", "Linden", "New Amsterdam"],
  "Haiti": ["Port-au-Prince", "Cap-Haïtien", "Gonaïves"],
  "Honduras": ["Tegucigalpa", "San Pedro Sula", "La Ceiba"],
  "Hungary": ["Budapest", "Debrecen", "Szeged", "Miskolc"],
  "Iceland": ["Reykjavík", "Kópavogur", "Hafnarfjörður"],
  "India": ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai", "Kolkata", "Pune", "Ahmedabad", "Jaipur", "Lucknow"],
  "Indonesia": ["Jakarta", "Surabaya", "Bandung", "Medan", "Semarang", "Makassar", "Palembang", "Tangerang", "Depok", "Bekasi"],
  "Iran": ["Tehran", "Mashhad", "Isfahan", "Karaj", "Shiraz", "Tabriz"],
  "Iraq": ["Baghdad", "Basra", "Mosul", "Erbil", "Sulaymaniyah"],
  "Ireland": ["Dublin", "Cork", "Limerick", "Galway", "Waterford"],
  "Israel": ["Jerusalem", "Tel Aviv", "Haifa", "Rishon LeZion", "Petah Tikva"],
  "Italy": ["Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna", "Florence", "Bari", "Catania"],
  "Jamaica": ["Kingston", "Montego Bay", "Spanish Town"],
  "Japan": ["Tokyo", "Yokohama", "Osaka", "Nagoya", "Sapporo", "Fukuoka", "Kobe", "Kyoto", "Kawasaki", "Saitama"],
  "Jordan": ["Amman", "Zarqa", "Irbid", "Aqaba"],
  "Kazakhstan": ["Almaty", "Nur-Sultan", "Shymkent", "Karaganda"],
  "Kenya": ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret"],
  "Kiribati": ["Tarawa", "Betio"],
  "Kosovo": ["Pristina", "Prizren", "Peja"],
  "Kuwait": ["Kuwait City", "Al Ahmadi", "Hawalli"],
  "Kyrgyzstan": ["Bishkek", "Osh", "Jalal-Abad"],
  "Laos": ["Vientiane", "Pakse", "Savannakhet"],
  "Latvia": ["Riga", "Daugavpils", "Liepāja"],
  "Lebanon": ["Beirut", "Tripoli", "Sidon", "Tyre"],
  "Lesotho": ["Maseru", "Teyateyaneng"],
  "Liberia": ["Monrovia", "Gbarnga"],
  "Libya": ["Tripoli", "Benghazi", "Misrata"],
  "Liechtenstein": ["Vaduz", "Schaan"],
  "Lithuania": ["Vilnius", "Kaunas", "Klaipėda"],
  "Luxembourg": ["Luxembourg City", "Esch-sur-Alzette"],
  "Madagascar": ["Antananarivo", "Toamasina", "Antsirabe"],
  "Malawi": ["Lilongwe", "Blantyre", "Mzuzu"],
  "Malaysia": ["Kuala Lumpur", "George Town", "Ipoh", "Shah Alam", "Petaling Jaya", "Johor Bahru", "Malacca City"],
  "Maldives": ["Malé", "Addu City"],
  "Mali": ["Bamako", "Sikasso", "Mopti"],
  "Malta": ["Valletta", "Birkirkara", "Mosta"],
  "Marshall Islands": ["Majuro", "Ebeye"],
  "Mauritania": ["Nouakchott", "Nouadhibou"],
  "Mauritius": ["Port Louis", "Beau Bassin-Rose Hill"],
  "Mexico": ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "León", "Juárez", "Zapopan", "Mérida", "Cancún"],
  "Micronesia": ["Palikir", "Weno"],
  "Moldova": ["Chișinău", "Tiraspol", "Bălți"],
  "Monaco": ["Monaco", "Monte Carlo"],
  "Mongolia": ["Ulaanbaatar", "Erdenet", "Darkhan"],
  "Montenegro": ["Podgorica", "Nikšić", "Pljevlja"],
  "Morocco": ["Casablanca", "Rabat", "Fes", "Marrakesh", "Tangier"],
  "Mozambique": ["Maputo", "Matola", "Beira", "Nampula"],
  "Myanmar": ["Yangon", "Mandalay", "Naypyidaw", "Mawlamyine"],
  "Namibia": ["Windhoek", "Walvis Bay", "Swakopmund"],
  "Nauru": ["Yaren"],
  "Nepal": ["Kathmandu", "Pokhara", "Lalitpur", "Bharatpur"],
  "Netherlands": ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven", "Tilburg", "Groningen", "Almere"],
  "New Zealand": ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga", "Dunedin"],
  "Nicaragua": ["Managua", "León", "Masaya", "Granada"],
  "Niger": ["Niamey", "Zinder", "Maradi"],
  "Nigeria": ["Lagos", "Kano", "Ibadan", "Abuja", "Port Harcourt", "Benin City"],
  "North Korea": ["Pyongyang", "Hamhung", "Chongjin"],
  "North Macedonia": ["Skopje", "Bitola", "Kumanovo"],
  "Norway": ["Oslo", "Bergen", "Stavanger", "Trondheim", "Drammen"],
  "Oman": ["Muscat", "Salalah", "Sohar"],
  "Pakistan": ["Karachi", "Lahore", "Faisalabad", "Rawalpindi", "Multan", "Islamabad", "Peshawar"],
  "Palau": ["Ngerulmud", "Koror"],
  "Palestine": ["Gaza City", "Ramallah", "Hebron", "Nablus"],
  "Panama": ["Panama City", "San Miguelito", "Tocumen"],
  "Papua New Guinea": ["Port Moresby", "Lae", "Mount Hagen"],
  "Paraguay": ["Asunción", "Ciudad del Este", "San Lorenzo"],
  "Peru": ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Cusco"],
  "Philippines": ["Manila", "Quezon City", "Davao City", "Caloocan", "Cebu City", "Zamboanga City"],
  "Poland": ["Warsaw", "Kraków", "Łódź", "Wrocław", "Poznań", "Gdańsk"],
  "Portugal": ["Lisbon", "Porto", "Amadora", "Braga", "Coimbra"],
  "Qatar": ["Doha", "Al Rayyan", "Umm Salal"],
  "Romania": ["Bucharest", "Cluj-Napoca", "Timișoara", "Iași", "Constanța"],
  "Russia": ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan", "Nizhny Novgorod", "Chelyabinsk"],
  "Rwanda": ["Kigali", "Butare", "Gitarama"],
  "Saint Kitts and Nevis": ["Basseterre", "Charlestown"],
  "Saint Lucia": ["Castries", "Vieux Fort"],
  "Saint Vincent and the Grenadines": ["Kingstown", "Georgetown"],
  "Samoa": ["Apia", "Vaitele"],
  "San Marino": ["San Marino", "Serravalle"],
  "Saudi Arabia": ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam"],
  "Senegal": ["Dakar", "Touba", "Thiès", "Saint-Louis"],
  "Serbia": ["Belgrade", "Novi Sad", "Niš", "Kragujevac"],
  "Seychelles": ["Victoria", "Anse Boileau"],
  "Sierra Leone": ["Freetown", "Bo", "Kenema"],
  "Singapore": ["Singapore"],
  "Slovakia": ["Bratislava", "Košice", "Prešov", "Žilina"],
  "Slovenia": ["Ljubljana", "Maribor", "Celje", "Kranj"],
  "Solomon Islands": ["Honiara", "Gizo"],
  "Somalia": ["Mogadishu", "Hargeisa", "Bosaso"],
  "South Africa": ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth", "Bloemfontein"],
  "South Korea": ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju"],
  "South Sudan": ["Juba", "Malakal", "Wau"],
  "Spain": ["Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza", "Málaga", "Murcia", "Palma", "Bilbao"],
  "Sri Lanka": ["Colombo", "Kandy", "Galle", "Jaffna"],
  "Sudan": ["Khartoum", "Omdurman", "Port Sudan"],
  "Suriname": ["Paramaribo", "Lelydorp"],
  "Sweden": ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Västerås"],
  "Switzerland": ["Zurich", "Geneva", "Basel", "Lausanne", "Bern"],
  "Syria": ["Damascus", "Aleppo", "Homs", "Latakia"],
  "Taiwan": ["Taipei", "Kaohsiung", "Taichung", "Tainan"],
  "Tajikistan": ["Dushanbe", "Khujand", "Kulob"],
  "Tanzania": ["Dar es Salaam", "Mwanza", "Arusha", "Dodoma"],
  "Thailand": ["Bangkok", "Chiang Mai", "Phuket", "Pattaya", "Hat Yai"],
  "Timor-Leste": ["Dili", "Baucau"],
  "Togo": ["Lomé", "Sokodé"],
  "Tonga": ["Nuku'alofa", "Neiafu"],
  "Trinidad and Tobago": ["Port of Spain", "San Fernando", "Chaguanas"],
  "Tunisia": ["Tunis", "Sfax", "Sousse", "Kairouan"],
  "Turkey": ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Adana"],
  "Turkmenistan": ["Ashgabat", "Türkmenabat", "Daşoguz"],
  "Tuvalu": ["Funafuti"],
  "Uganda": ["Kampala", "Gulu", "Lira", "Mbarara"],
  "Ukraine": ["Kyiv", "Kharkiv", "Odesa", "Dnipro", "Lviv"],
  "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah", "Al Ain", "Ajman"],
  "United Kingdom": ["London", "Birmingham", "Manchester", "Leeds", "Glasgow", "Liverpool", "Newcastle", "Sheffield", "Bristol", "Edinburgh"],
  "United States": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose", "Austin", "Jacksonville", "Fort Worth", "Columbus", "Charlotte", "San Francisco", "Indianapolis", "Seattle", "Denver", "Washington", "Boston", "Nashville", "Detroit", "Portland", "Las Vegas", "Miami", "Atlanta"],
  "Uruguay": ["Montevideo", "Salto", "Paysandú", "Maldonado"],
  "Uzbekistan": ["Tashkent", "Samarkand", "Namangan", "Andijan"],
  "Vanuatu": ["Port Vila", "Luganville"],
  "Vatican City": ["Vatican City"],
  "Venezuela": ["Caracas", "Maracaibo", "Valencia", "Barquisimeto"],
  "Vietnam": ["Ho Chi Minh City", "Hanoi", "Da Nang", "Haiphong", "Can Tho"],
  "Yemen": ["Sana'a", "Aden", "Taiz", "Hodeidah"],
  "Zambia": ["Lusaka", "Kitwe", "Ndola", "Kabwe"],
  "Zimbabwe": ["Harare", "Bulawayo", "Chitungwiza", "Mutare"]
};

export const COUNTRY_FLAGS = {
  "Afghanistan": "🇦🇫", "Albania": "🇦🇱", "Algeria": "🇩🇿", "Andorra": "🇦🇩",
  "Angola": "🇦🇴", "Argentina": "🇦🇷", "Armenia": "🇦🇲", "Australia": "🇦🇺",
  "Austria": "🇦🇹", "Azerbaijan": "🇦🇿", "Bahamas": "🇧🇸", "Bahrain": "🇧🇭",
  "Bangladesh": "🇧🇩", "Barbados": "🇧🇧", "Belarus": "🇧🇾", "Belgium": "🇧🇪",
  "Belize": "🇧🇿", "Benin": "🇧🇯", "Bhutan": "🇧🇹", "Bolivia": "🇧🇴",
  "Bosnia and Herzegovina": "🇧🇦", "Botswana": "🇧🇼", "Brazil": "🇧🇷",
  "Brunei": "🇧🇳", "Bulgaria": "🇧🇬", "Burkina Faso": "🇧🇫", "Burundi": "🇧🇮",
  "Cambodia": "🇰🇭", "Cameroon": "🇨🇲", "Canada": "🇨🇦", "Cape Verde": "🇨🇻",
  "Central African Republic": "🇨🇫", "Chad": "🇹🇩", "Chile": "🇨🇱", "China": "🇨🇳",
  "Colombia": "🇨🇴", "Comoros": "🇰🇲", "Congo": "🇨🇬", "Costa Rica": "🇨🇷",
  "Croatia": "🇭🇷", "Cuba": "🇨🇺", "Cyprus": "🇨🇾", "Czech Republic": "🇨🇿",
  "Denmark": "🇩🇰", "Djibouti": "🇩🇯", "Dominica": "🇩🇲",
  "Dominican Republic": "🇩🇴", "Ecuador": "🇪🇨", "Egypt": "🇪🇬",
  "El Salvador": "🇸🇻", "Equatorial Guinea": "🇬🇶", "Eritrea": "🇪🇷",
  "Estonia": "🇪🇪", "Eswatini": "🇸🇿", "Ethiopia": "🇪🇹", "Fiji": "🇫🇯",
  "Finland": "🇫🇮", "France": "🇫🇷", "Gabon": "🇬🇦", "Gambia": "🇬🇲",
  "Georgia": "🇬🇪", "Germany": "🇩🇪", "Ghana": "🇬🇭", "Greece": "🇬🇷",
  "Grenada": "🇬🇩", "Guatemala": "🇬🇹", "Guinea": "🇬🇳", "Guinea-Bissau": "🇬🇼",
  "Guyana": "🇬🇾", "Haiti": "🇭🇹", "Honduras": "🇭🇳", "Hungary": "🇭🇺",
  "Iceland": "🇮🇸", "India": "🇮🇳", "Indonesia": "🇮🇩", "Iran": "🇮🇷",
  "Iraq": "🇮🇶", "Ireland": "🇮🇪", "Israel": "🇮🇱", "Italy": "🇮🇹",
  "Jamaica": "🇯🇲", "Japan": "🇯🇵", "Jordan": "🇯🇴", "Kazakhstan": "🇰🇿",
  "Kenya": "🇰🇪", "Kiribati": "🇰🇮", "Kosovo": "🇽🇰", "Kuwait": "🇰🇼",
  "Kyrgyzstan": "🇰🇬", "Laos": "🇱🇦", "Latvia": "🇱🇻", "Lebanon": "🇱🇧",
  "Lesotho": "🇱🇸", "Liberia": "🇱🇷", "Libya": "🇱🇾", "Liechtenstein": "🇱🇮",
  "Lithuania": "🇱🇹", "Luxembourg": "🇱🇺", "Madagascar": "🇲🇬", "Malawi": "🇲🇼",
  "Malaysia": "🇲🇾", "Maldives": "🇲🇻", "Mali": "🇲🇱", "Malta": "🇲🇹",
  "Marshall Islands": "🇲🇭", "Mauritania": "🇲🇷", "Mauritius": "🇲🇺",
  "Mexico": "🇲🇽", "Micronesia": "🇫🇲", "Moldova": "🇲🇩", "Monaco": "🇲🇨",
  "Mongolia": "🇲🇳", "Montenegro": "🇲🇪", "Morocco": "🇲🇦", "Mozambique": "🇲🇿",
  "Myanmar": "🇲🇲", "Namibia": "🇳🇦", "Nauru": "🇳🇷", "Nepal": "🇳🇵",
  "Netherlands": "🇳🇱", "New Zealand": "🇳🇿", "Nicaragua": "🇳🇮", "Niger": "🇳🇪",
  "Nigeria": "🇳🇬", "North Korea": "🇰🇵", "North Macedonia": "🇲🇰", "Norway": "🇳🇴",
  "Oman": "🇴🇲", "Pakistan": "🇵🇰", "Palau": "🇵🇼", "Palestine": "🇵🇸",
  "Panama": "🇵🇦", "Papua New Guinea": "🇵🇬", "Paraguay": "🇵🇾", "Peru": "🇵🇪",
  "Philippines": "🇵🇭", "Poland": "🇵🇱", "Portugal": "🇵🇹", "Qatar": "🇶🇦",
  "Romania": "🇷🇴", "Russia": "🇷🇺", "Rwanda": "🇷🇼",
  "Saint Kitts and Nevis": "🇰🇳", "Saint Lucia": "🇱🇨",
  "Saint Vincent and the Grenadines": "🇻🇨", "Samoa": "🇼🇸",
  "San Marino": "🇸🇲", "Saudi Arabia": "🇸🇦", "Senegal": "🇸🇳", "Serbia": "🇷🇸",
  "Seychelles": "🇸🇨", "Sierra Leone": "🇸🇱", "Singapore": "🇸🇬",
  "Slovakia": "🇸🇰", "Slovenia": "🇸🇮", "Solomon Islands": "🇸🇧",
  "Somalia": "🇸🇴", "South Africa": "🇿🇦", "South Korea": "🇰🇷",
  "South Sudan": "🇸🇸", "Spain": "🇪🇸", "Sri Lanka": "🇱🇰", "Sudan": "🇸🇩",
  "Suriname": "🇸🇷", "Sweden": "🇸🇪", "Switzerland": "🇨🇭", "Syria": "🇸🇾",
  "Taiwan": "🇹🇼", "Tajikistan": "🇹🇯", "Tanzania": "🇹🇿", "Thailand": "🇹🇭",
  "Timor-Leste": "🇹🇱", "Togo": "🇹🇬", "Tonga": "🇹🇴",
  "Trinidad and Tobago": "🇹🇹", "Tunisia": "🇹🇳", "Turkey": "🇹🇷",
  "Turkmenistan": "🇹🇲", "Tuvalu": "🇹🇻", "Uganda": "🇺🇬", "Ukraine": "🇺🇦",
  "United Arab Emirates": "🇦🇪", "United Kingdom": "🇬🇧", "United States": "🇺🇸",
  "Uruguay": "🇺🇾", "Uzbekistan": "🇺🇿", "Vanuatu": "🇻🇺",
  "Vatican City": "🇻🇦", "Venezuela": "🇻🇪", "Vietnam": "🇻🇳", "Yemen": "🇾🇪",
  "Zambia": "🇿🇲", "Zimbabwe": "🇿🇼"
};