// Top universities by country - Organized by region

export const UNIVERSITIES_BY_COUNTRY = {
  // United States
  "United States": [
    "Harvard University",
    "Stanford University",
    "Massachusetts Institute of Technology (MIT)",
    "California Institute of Technology (Caltech)",
    "Princeton University",
    "Yale University",
    "Columbia University",
    "University of Pennsylvania",
    "Cornell University",
    "Duke University",
    "Northwestern University",
    "Johns Hopkins University",
    "University of California, Berkeley",
    "University of California, Los Angeles (UCLA)",
    "University of Southern California (USC)",
    "University of Michigan",
    "New York University (NYU)",
    "Carnegie Mellon University",
    "University of Chicago",
    "Brown University",
    "Dartmouth College",
    "Vanderbilt University",
    "Rice University",
    "Georgetown University",
    "University of Virginia",
    "Emory University",
    "University of California, San Diego",
    "Boston University",
    "University of Texas at Austin",
    "University of Washington",
    "Georgia Institute of Technology",
    "University of North Carolina at Chapel Hill",
    "University of Wisconsin-Madison",
    "University of Illinois Urbana-Champaign",
    "Ohio State University",
    "Pennsylvania State University",
    "Purdue University",
    "University of Florida",
    "University of Maryland",
    "University of California, Irvine",
    "University of California, Davis",
    "University of California, Santa Barbara",
    "University of Minnesota",
    "Arizona State University",
    "University of Colorado Boulder",
    "Indiana University",
    "Michigan State University",
    "Texas A&M University",
    "Virginia Tech",
    "Rutgers University"
  ],

  // United Kingdom
  "United Kingdom": [
    "University of Oxford",
    "University of Cambridge",
    "Imperial College London",
    "University College London (UCL)",
    "London School of Economics (LSE)",
    "King's College London",
    "University of Edinburgh",
    "University of Manchester",
    "University of Bristol",
    "University of Warwick",
    "University of Glasgow",
    "Durham University",
    "University of Birmingham",
    "University of Southampton",
    "University of Leeds",
    "University of Sheffield",
    "Queen Mary University of London",
    "Lancaster University",
    "University of Nottingham",
    "University of York",
    "University of Liverpool",
    "University of Bath",
    "University of Exeter",
    "Cardiff University",
    "Newcastle University",
    "University of St Andrews",
    "University of Aberdeen",
    "University of Sussex",
    "University of Leicester",
    "Loughborough University",
    "University of Reading",
    "Royal Holloway, University of London",
    "University of Surrey",
    "Queen's University Belfast",
    "University of Dundee",
    "Heriot-Watt University",
    "Swansea University",
    "University of East Anglia",
    "University of Kent",
    "Brunel University London"
  ],

  // Canada
  "Canada": [
    "University of Toronto",
    "University of British Columbia",
    "McGill University",
    "McMaster University",
    "University of Montreal",
    "University of Alberta",
    "University of Waterloo",
    "Western University",
    "Queen's University",
    "University of Calgary",
    "Simon Fraser University",
    "Dalhousie University",
    "University of Ottawa",
    "York University",
    "University of Victoria",
    "Carleton University",
    "Concordia University",
    "Université Laval",
    "University of Manitoba",
    "University of Saskatchewan",
    "Memorial University of Newfoundland",
    "Ryerson University",
    "University of Guelph",
    "University of Regina",
    "Brock University",
    "Wilfrid Laurier University",
    "University of Windsor",
    "Lakehead University",
    "University of New Brunswick",
    "Mount Allison University"
  ],

  // Australia
  "Australia": [
    "University of Melbourne",
    "Australian National University (ANU)",
    "University of Sydney",
    "University of New South Wales (UNSW)",
    "University of Queensland",
    "Monash University",
    "University of Western Australia",
    "University of Adelaide",
    "University of Technology Sydney (UTS)",
    "Queensland University of Technology (QUT)",
    "RMIT University",
    "Curtin University",
    "Macquarie University",
    "University of Wollongong",
    "Deakin University",
    "Griffith University",
    "University of Newcastle",
    "University of South Australia",
    "La Trobe University",
    "Flinders University",
    "James Cook University",
    "University of Tasmania",
    "Swinburne University of Technology",
    "Western Sydney University",
    "Victoria University",
    "Bond University",
    "Charles Darwin University",
    "Australian Catholic University",
    "University of Canberra",
    "Southern Cross University"
  ],

  // India
  "India": [
    "Indian Institute of Technology (IIT) Bombay",
    "Indian Institute of Technology (IIT) Delhi",
    "Indian Institute of Technology (IIT) Madras",
    "Indian Institute of Technology (IIT) Kanpur",
    "Indian Institute of Technology (IIT) Kharagpur",
    "Indian Institute of Technology (IIT) Roorkee",
    "Indian Institute of Technology (IIT) Guwahati",
    "Indian Institute of Technology (IIT) Hyderabad",
    "Indian Institute of Science (IISc) Bangalore",
    "Delhi University",
    "Jawaharlal Nehru University (JNU)",
    "Banaras Hindu University",
    "University of Calcutta",
    "University of Mumbai",
    "Anna University",
    "Jadavpur University",
    "Amity University",
    "Manipal Academy of Higher Education",
    "Vellore Institute of Technology (VIT)",
    "Birla Institute of Technology and Science (BITS Pilani)",
    "National Institute of Technology (NIT) Trichy",
    "National Institute of Technology (NIT) Warangal",
    "International Institute of Information Technology (IIIT) Hyderabad",
    "Indian Institute of Technology (IIT) BHU Varanasi",
    "Symbiosis International University",
    "SRM Institute of Science and Technology",
    "PSG College of Technology",
    "SASTRA University",
    "Thapar Institute of Engineering and Technology",
    "Indian Statistical Institute"
  ],

  // China
  "China": [
    "Tsinghua University",
    "Peking University",
    "Fudan University",
    "Shanghai Jiao Tong University",
    "Zhejiang University",
    "University of Science and Technology of China",
    "Nanjing University",
    "Wuhan University",
    "Harbin Institute of Technology",
    "Xi'an Jiaotong University",
    "Beijing Normal University",
    "Sun Yat-sen University",
    "Tongji University",
    "Nankai University",
    "Tianjin University",
    "Renmin University of China",
    "Beijing Institute of Technology",
    "Sichuan University",
    "Southeast University",
    "Xiamen University"
  ],

  // Germany
  "Germany": [
    "Technical University of Munich",
    "Ludwig Maximilian University of Munich",
    "Heidelberg University",
    "Humboldt University of Berlin",
    "Free University of Berlin",
    "RWTH Aachen University",
    "University of Freiburg",
    "University of Tübingen",
    "University of Göttingen",
    "University of Bonn",
    "University of Hamburg",
    "Karlsruhe Institute of Technology",
    "University of Cologne",
    "University of Mannheim",
    "Technical University of Berlin",
    "University of Stuttgart",
    "University of Frankfurt",
    "University of Münster",
    "University of Würzburg",
    "University of Erlangen-Nuremberg"
  ],

  // France
  "France": [
    "Sorbonne University",
    "École Polytechnique",
    "École Normale Supérieure (ENS Paris)",
    "Sciences Po Paris",
    "Université PSL",
    "CentraleSupélec",
    "École des Ponts ParisTech",
    "University of Paris",
    "Grenoble Alpes University",
    "Aix-Marseille University",
    "University of Strasbourg",
    "University of Montpellier",
    "University of Lyon",
    "University of Bordeaux",
    "University of Lille",
    "University of Toulouse",
    "HEC Paris",
    "ESSEC Business School",
    "INSEAD",
    "EDHEC Business School"
  ],

  // Singapore
  "Singapore": [
    "National University of Singapore (NUS)",
    "Nanyang Technological University (NTU)",
    "Singapore Management University (SMU)",
    "Singapore University of Technology and Design (SUTD)",
    "Singapore Institute of Technology (SIT)",
    "Singapore University of Social Sciences (SUSS)"
  ],

  // Japan
  "Japan": [
    "University of Tokyo",
    "Kyoto University",
    "Tokyo Institute of Technology",
    "Osaka University",
    "Tohoku University",
    "Nagoya University",
    "Kyushu University",
    "Hokkaido University",
    "Keio University",
    "Waseda University",
    "Tokyo Medical and Dental University",
    "Hitotsubashi University",
    "Tsukuba University",
    "Kobe University",
    "Yokohama National University",
    "Chiba University",
    "Okayama University",
    "Kanazawa University",
    "Hiroshima University",
    "Niigata University"
  ],

  // South Korea
  "South Korea": [
    "Seoul National University",
    "Korea Advanced Institute of Science and Technology (KAIST)",
    "Yonsei University",
    "Korea University",
    "Sungkyunkwan University",
    "Hanyang University",
    "Pohang University of Science and Technology (POSTECH)",
    "Kyung Hee University",
    "Ewha Womans University",
    "Sogang University",
    "Chung-Ang University",
    "Konkuk University",
    "Inha University",
    "Ajou University",
    "Pusan National University"
  ],

  // Netherlands
  "Netherlands": [
    "University of Amsterdam",
    "Delft University of Technology",
    "Utrecht University",
    "Leiden University",
    "University of Groningen",
    "Erasmus University Rotterdam",
    "Eindhoven University of Technology",
    "Wageningen University",
    "Radboud University",
    "Maastricht University",
    "VU University Amsterdam",
    "University of Twente",
    "Tilburg University",
    "Rotterdam School of Management"
  ],

  // Switzerland
  "Switzerland": [
    "ETH Zurich",
    "École Polytechnique Fédérale de Lausanne (EPFL)",
    "University of Zurich",
    "University of Geneva",
    "University of Bern",
    "University of Basel",
    "University of Lausanne",
    "University of St. Gallen",
    "University of Fribourg",
    "University of Neuchâtel"
  ],

  // New Zealand
  "New Zealand": [
    "University of Auckland",
    "University of Otago",
    "Victoria University of Wellington",
    "University of Canterbury",
    "Massey University",
    "University of Waikato",
    "Lincoln University",
    "Auckland University of Technology (AUT)"
  ]
};
